import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/molecule/Header";
import Footer from "@/components/molecule/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <Header />
        <div className="flex justify-center w-full pt-[5rem] py-5">
          <div className=" flex flex-col w-[950px] ">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
